name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: go build
      - if: startsWith(github.ref, 'refs/tags/')
        run: |
          export VERSION="${github_ref/refs/\/tags\/v/}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          tar -czvf gcs-cacher_$VERSION_linux_amd64.tgz gcs-cacher
          sha256sum gcs-cacher_$VERSION_linux_amd64.tgz > gcs-cacher_$VERSION_SHA256SUMS
        env:
          github_ref: ${{ github.ref }}
      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: gcs-cacher_${{ env.VERSION }}_linux_amd64.tgz
          path: ./gcs-cacher_${{ env.VERSION }}_linux_amd64.tgz
      - if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v2
        with:
          name: gcs-cacher_${{ env.VERSION }}_SHA256SUMS
          path: ./gcs-cacher_${{ env.VERSION }}_SHA256SUMS

