name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: go build
      - uses: actions/upload-artifact@v2
        with:
          name: gcs-cacher
          path: ./gcs-cacher

